Traceback (most recent call last):
  File "main.py", line 1, in <module>
    with open('~/Documents/test.out', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/test.out'
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    with open('~/Documents/test.out', 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/test.out'
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    with open('~/Documents/test.out', 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/test.out'
